import type { Language } from "@/lib/i18n/languages";

/**
 * Search-friendly rashifal pages (/rashifal/<lang>/<sign>) for the languages
 * people search astrology in. Sign names are written out by hand — not machine
 * translated — because they are what people type into Google.
 */
export const SEO_LANGUAGES = [
  "hi",
  "en",
  "mr",
  "bn",
  "gu",
  "pa",
  "or",
  "te",
  "ta",
  "kn",
  "ml",
  "de",
] as const satisfies readonly Language[];
export type SeoLanguage = (typeof SEO_LANGUAGES)[number];

export function isSeoLanguage(code: string): code is SeoLanguage {
  return (SEO_LANGUAGES as readonly string[]).includes(code);
}

/** Sign names, Mesha → Meena, in each language. */
export const SIGN_NAMES: Record<SeoLanguage, readonly string[]> = {
  hi: [
    "मेष",
    "वृषभ",
    "मिथुन",
    "कर्क",
    "सिंह",
    "कन्या",
    "तुला",
    "वृश्चिक",
    "धनु",
    "मकर",
    "कुंभ",
    "मीन",
  ],
  mr: [
    "मेष",
    "वृषभ",
    "मिथुन",
    "कर्क",
    "सिंह",
    "कन्या",
    "तूळ",
    "वृश्चिक",
    "धनु",
    "मकर",
    "कुंभ",
    "मीन",
  ],
  bn: [
    "মেষ",
    "বৃষ",
    "মিথুন",
    "কর্কট",
    "সিংহ",
    "কন্যা",
    "তুলা",
    "বৃশ্চিক",
    "ধনু",
    "মকর",
    "কুম্ভ",
    "মীন",
  ],
  gu: [
    "મેષ",
    "વૃષભ",
    "મિથુન",
    "કર્ક",
    "સિંહ",
    "કન્યા",
    "તુલા",
    "વૃશ્ચિક",
    "ધન",
    "મકર",
    "કુંભ",
    "મીન",
  ],
  pa: [
    "ਮੇਖ",
    "ਬ੍ਰਿਖ",
    "ਮਿਥੁਨ",
    "ਕਰਕ",
    "ਸਿੰਘ",
    "ਕੰਨਿਆ",
    "ਤੁਲਾ",
    "ਬ੍ਰਿਸ਼ਚਕ",
    "ਧਨੁ",
    "ਮਕਰ",
    "ਕੁੰਭ",
    "ਮੀਨ",
  ],
  or: [
    "ମେଷ",
    "ବୃଷ",
    "ମିଥୁନ",
    "କର୍କଟ",
    "ସିଂହ",
    "କନ୍ୟା",
    "ତୁଳା",
    "ବୃଶ୍ଚିକ",
    "ଧନୁ",
    "ମକର",
    "କୁମ୍ଭ",
    "ମୀନ",
  ],
  te: [
    "మేషం",
    "వృషభం",
    "మిథునం",
    "కర్కాటకం",
    "సింహం",
    "కన్య",
    "తుల",
    "వృశ్చికం",
    "ధనుస్సు",
    "మకరం",
    "కుంభం",
    "మీనం",
  ],
  ta: [
    "மேஷம்",
    "ரிஷபம்",
    "மிதுனம்",
    "கடகம்",
    "சிம்மம்",
    "கன்னி",
    "துலாம்",
    "விருச்சிகம்",
    "தனுசு",
    "மகரம்",
    "கும்பம்",
    "மீனம்",
  ],
  kn: [
    "ಮೇಷ",
    "ವೃಷಭ",
    "ಮಿಥುನ",
    "ಕರ್ಕಾಟಕ",
    "ಸಿಂಹ",
    "ಕನ್ಯಾ",
    "ತುಲಾ",
    "ವೃಶ್ಚಿಕ",
    "ಧನು",
    "ಮಕರ",
    "ಕುಂಭ",
    "ಮೀನ",
  ],
  ml: [
    "മേടം",
    "ഇടവം",
    "മിഥുനം",
    "കർക്കടകം",
    "ചിങ്ങം",
    "കന്നി",
    "തുലാം",
    "വൃശ്ചികം",
    "ധനു",
    "മകരം",
    "കുംഭം",
    "മീനം",
  ],
  en: [
    "Aries",
    "Taurus",
    "Gemini",
    "Cancer",
    "Leo",
    "Virgo",
    "Libra",
    "Scorpio",
    "Sagittarius",
    "Capricorn",
    "Aquarius",
    "Pisces",
  ],
  de: [
    "Widder",
    "Stier",
    "Zwillinge",
    "Krebs",
    "Löwe",
    "Jungfrau",
    "Waage",
    "Skorpion",
    "Schütze",
    "Steinbock",
    "Wassermann",
    "Fische",
  ],
};

/** "<sign> + this phrase" is the search title, e.g. "मेष राशिफल आज". */
export const TODAY_PHRASE: Record<SeoLanguage, string> = {
  hi: "राशिफल आज",
  mr: "राशीभविष्य आज",
  bn: "রাশিফল আজ",
  gu: "રાશિફળ આજે",
  pa: "ਰਾਸ਼ੀਫਲ ਅੱਜ",
  or: "ରାଶିଫଳ ଆଜି",
  te: "రాశిఫలం ఈరోజు",
  ta: "ராசி பலன் இன்று",
  kn: "ರಾಶಿ ಭವಿಷ್ಯ ಇಂದು",
  ml: "രാശിഫലം ഇന്ന്",
  en: "Horoscope Today",
  de: "Horoskop heute",
};

/** Heading for the list of all 12 signs, e.g. "आज का राशिफल". */
export const INDEX_TITLE: Record<SeoLanguage, string> = {
  hi: "आज का राशिफल",
  mr: "आजचे राशीभविष्य",
  bn: "আজকের রাশিফল",
  gu: "આજનું રાશિફળ",
  pa: "ਅੱਜ ਦਾ ਰਾਸ਼ੀਫਲ",
  or: "ଆଜିର ରାଶିଫଳ",
  te: "ఈరోజు రాశిఫలాలు",
  ta: "இன்றைய ராசி பலன்",
  kn: "ಇಂದಿನ ರಾಶಿ ಭವಿಷ್ಯ",
  ml: "ഇന്നത്തെ രാശിഫലം",
  en: "Today's Horoscope (Rashifal)",
  de: "Horoskop für heute",
};

export function seoTitle(lang: SeoLanguage, sign: number): string {
  return `${SIGN_NAMES[lang][sign]} ${TODAY_PHRASE[lang]}`;
}
